# Configuration file for MegaLinter
# See all available variables at https://oxsecurity.github.io/megalinter/configuration/ and in linters documentation

APPLY_FIXES: none # all, none, or list of linter keys
# ENABLE: # If you use ENABLE variable, all other languages/formats/tooling-formats will be disabled by default
# ENABLE_LINTERS: # If you use ENABLE_LINTERS variable, all other linters will be disabled by default
DISABLE:
  - COPYPASTE # Uncomment to disable checks of excessive copy-pastes
  - SPELL # Uncomment to disable checks of spelling mistakes
  - YAML
DISABLE_LINTERS:
  - MARKDOWN_MARKDOWN_LINK_CHECK
  - MARKDOWN_MARKDOWN_TABLE_FORMATTER
  - REPOSITORY_SEMGREP
  # False positive: error - python package "--hash" is available for public registration. /github/workspace/requirements.txt
  # Also seems to be an inactive project.
  - REPOSITORY_DUSTILOCK
SHOW_ELAPSED_TIME: true
FILEIO_REPORTER: false
# DISABLE_ERRORS: true # Uncomment if you want MegaLinter to detect errors but not block CI to pass
REPOSITORY_TRIVY_ARGUMENTS:
  - "--severity=MEDIUM,HIGH,CRITICAL"

BASH_SHFMT_ARGUMENTS:
  - "--indent=2"

REPOSITORY_KICS_CONFIG_FILE: ".kics.yaml"
