name: check links

on:
  repository_dispatch:
  workflow_dispatch:
  schedule:
    - cron: "00 18 * * *"

permissions: read-all

jobs:
  check-links:
    runs-on: ubuntu-24.04
    permissions:
      issues: write
    steps:
      - uses: actions/checkout@d632683dd7b4114ad314bca15554477dd762a938 # v4.2.0

      - name: Link Checker
        id: lychee
        uses: lycheeverse/lychee-action@2b973e86fc7b1f6b36a93795fe2c9c6ae1118621 # v1.10.0
        with:
          args: "--config=.lychee.toml ."
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

      - name: Look for an existing issue
        id: last-issue
        uses: micalevisk/last-issue-action@0d40124cc99ac8601c2516007f0c98ef3d27537b # v2.3.0
        with:
          state: open
          labels: link-check

      - name: Create Issue From File
        if: ${{ env.lychee_exit_code != 0 }}
        uses: peter-evans/create-issue-from-file@e8ef132d6df98ed982188e460ebb3b5d4ef3a9cd # v5.0.1
        with:
          title: Link Checker Report
          content-filepath: ./lychee/out.md
          issue-number: ${{ steps.last-issue.outputs.issue_number }}
          labels: report, automated issue, link-check
