name: ci

on:
  push:
    branches: [master]
  release:
    types: [created]
  pull_request:
    branches: [master]

permissions: read-all

jobs:
  build:
    uses: chgl/.github/.github/workflows/standard-build.yaml@888b17087ecf83c5c06305540fe43bf99e2e37fe # v1.4.12
    permissions:
      contents: read
      id-token: write
      packages: write
      pull-requests: write
      actions: read
      security-events: write
    with:
      enable-build-test-layer: false
      enable-upload-test-image: false
    secrets:
      github-token: ${{ secrets.GITHUB_TOKEN }}

  lint:
    uses: chgl/.github/.github/workflows/standard-lint.yaml@888b17087ecf83c5c06305540fe43bf99e2e37fe # v1.4.12
    permissions:
      contents: read
      pull-requests: write
      issues: write
      security-events: write
      actions: read
    with:
      enable-codeql: false
    secrets:
      github-token: ${{ secrets.GITHUB_TOKEN }}

  release:
    uses: chgl/.github/.github/workflows/standard-release.yaml@888b17087ecf83c5c06305540fe43bf99e2e37fe # v1.4.12
    needs:
      - build
    permissions:
      contents: write
      pull-requests: write
      issues: write
    secrets:
      semantic-release-token: ${{ secrets.CI_SEMANTIC_RELEASE_TOKEN }}

  copy-image-to-dockerhub:
    name: copy ghcr.io image to DockerHub
    if: ${{ github.event_name != 'pull_request' }}
    runs-on: ubuntu-22.04
    needs:
      - build
    steps:
      - uses: imjasonh/setup-crane@00c9e93efa4e1138c9a7a5c594acd6c75a2fbf0c # v0.3
      - name: Login to DockerHub
        env:
          DOCKERHUB_TOKEN: "${{ secrets.DOCKERHUB_TOKEN }}"
        run: |
          echo "${DOCKERHUB_TOKEN}" | crane auth login docker.io --username chgl --password-stdin
      - name: Copy all tags
        env:
          TAGS: ${{ needs.build.outputs.image-tags }}
        run: |
          echo "${TAGS}" | while read -r tag; do crane copy "$tag" "${tag/ghcr.io/docker.io}"; done
