name: ci

on:
  push:
    branches: [master]
  release:
    types: [created]
  pull_request:
    branches: [master]

permissions:
  contents: read

jobs:
  build:
    uses: chgl/.github/.github/workflows/standard-build.yaml@a70808072e4df6003d21ea0255938271aa6b535d # v1.10.5
    permissions:
      contents: write
      id-token: write
      packages: write
      pull-requests: write
      actions: read
      security-events: write
    with:
      enable-build-test-layer: false
      enable-upload-test-image: false
    secrets:
      github-token: ${{ secrets.GITHUB_TOKEN }}

  lint:
    uses: chgl/.github/.github/workflows/standard-lint.yaml@a70808072e4df6003d21ea0255938271aa6b535d # v1.10.5
    permissions:
      contents: read
      pull-requests: write
      issues: write
      security-events: write
      actions: read
    with:
      enable-codeql: false
      enable-validate-gradle-wrapper: false
      enable-verify-base-image-signature: false
    secrets:
      github-token: ${{ secrets.GITHUB_TOKEN }}

  release:
    uses: chgl/.github/.github/workflows/standard-release.yaml@a70808072e4df6003d21ea0255938271aa6b535d # v1.10.5
    needs:
      - build
    permissions:
      contents: write
      pull-requests: write
      issues: write
    with:
      use-app-token: true
    secrets:
      app-token-app-id: ${{ secrets.RELEASER_APP_ID }}
      app-token-private-key: ${{ secrets.RELEASER_APP_PRIVATE_KEY }}

  copy-image-to-dockerhub:
    name: copy ghcr.io image to DockerHub
    if: ${{ github.event_name != 'pull_request' }}
    runs-on: ubuntu-24.04
    needs:
      - build
    steps:
      - uses: imjasonh/setup-crane@31b88efe9de28ae0ffa220711af4b60be9435f6e # v0.4
      - name: Login to DockerHub
        env:
          DOCKERHUB_TOKEN: "${{ secrets.DOCKERHUB_TOKEN }}"
        run: |
          echo "${DOCKERHUB_TOKEN}" | crane auth login docker.io --username chgl --password-stdin
      - name: Copy all tags
        env:
          TAGS: ${{ needs.build.outputs.image-tags }}
        run: |
          echo "${TAGS}" | while read -r tag; do crane copy "$tag" "${tag/ghcr.io/docker.io}"; done
