name: scan
on:
  schedule:
    - cron: "0 8 * * *"

# Declare default permissions as read only.
permissions: read-all

jobs:
  scan:
    name: Scan
    runs-on: ubuntu-22.04
    permissions:
      security-events: write # for github/codeql-action/upload-sarif to upload SARIF results
    steps:
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@91713af97dc80187565512baba96e4364e983601 # 0.16.0
        with:
          image-ref: "ghcr.io/chgl/kube-powertools:latest"
          format: "template"
          template: "@/contrib/sarif.tpl"
          output: "trivy-results.sarif"
          severity: "CRITICAL,HIGH"

      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@1500a131381b66de0c52ac28abb13cd79f4b7ecc # v2.22.12
        with:
          sarif_file: "trivy-results.sarif"
